/**
 * @Description: Types Redux
 * @Created by ZiniTeam
 * @Date create: 17/01/2019
 */
/** LOADING */
export const SET_LOADING = 'SET_LOADING';

/** SETTING */
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';

/** CONNECTION */
export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS';

/** SOCKET */
export const SOCKET_INIT = 'SOCKET_INIT';

/* LOGIN TYPE */
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const LOG_OUT_USER = 'LOG_OUT_USER';

/* PROFILE TYPE */
export const FETCH_CHANGE_INFO = 'FETCH_CHANGE_INFO';
export const FETCH_CHANGE_SUCCESS = 'FETCH_CHANGE_SUCCESS';
export const FETCH_CHANGE_FAILED = 'FETCH_CHANGE_FAILED';

/* HOME TYPE */
export const FETCH_HOME_INFO = 'FETCH_HOME_INFO';
export const FETCH_HOME_SUCCESS = 'FETCH_HOME_SUCCESS';
export const FETCH_HOME_FAILED = 'FETCH_HOME_FAILED';

/** MESSAGES TYPE */
export const SAVE_MESSAGES_DATA_NOT_READ = 'SAVE_MESSAGES_DATA_NOT_READ';

/* NEWS TYPE */
export const FETCH_NEWS_INFO = 'FETCH_NEWS_INFO';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';

/* NOTIFICATION TYPE */
export const FETCH_NOTIFICATION_INFO = 'FETCH_NOTIFICATION_INFO';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const FETCH_NOTIFICATION_FAILED = 'FETCH_NOTIFICATION_FAILED';
export const SAVE_NOTIFICATION_DATA_NOT_READ =
  'SAVE_NOTIFICATION_DATA_NOT_READ';

/* ALBUMS TYPE */
export const FETCH_ALBUM_INFO = 'FETCH_ALBUM_INFO';
export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS';
export const FETCH_ALBUM_FAILED = 'FETCH_ALBUM_FAILED';

/* HEALTH TYPE */
export const FETCH_HEALTH_INFO = 'FETCH_HEALTH_INFO';
export const FETCH_HEALTH_SUCCESS = 'FETCH_HEALTH_SUCCESS';
export const FETCH_HEALTH_FAILED = 'FETCH_HEALTH_FAILED';

/* ATTENDANT */
export const FETCH_ATTENDANT_INFO = 'FETCH_ATTENDANT_INFO';
export const FETCH_ATTENDANT_SUCCESS = 'FETCH_ATTENDANT_SUCCESS';
export const FETCH_ATTENDANT_FAILED = 'FETCH_ATTENDANT_FAILED';

/* MASTER DATA */
export const GET_MASTER_PARENTS_SUCCESS = 'GET_MASTER_PARENTS_SUCCESS';
export const GET_MASTER_TEACHERS_SUCCESS = 'GET_MASTER_TEACHERS_SUCCESS';

/* SCHOOL DATA */
export const GET_SCHOOL_SUCCESS = 'GET_SCHOOL_SUCCESS';

/** LANG */
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

/** CLASS */
export const CHANGE_CLASS = 'CHANGE_CLASS';

/** STUDENT */
export const CHANGE_STUDENT = 'CHANGE_STUDENT';
